name: ols-stats
channels:
- conda-forge
- defaults
dependencies:
- jupyter
- matplotlib
- pandas
- pygithub
- pyyaml
- pycountry
- geopy
- geopandas
- plotly
- notebook
- ipywidgets
- yt-dlp
- python-kaleido
- jupyter-book
