name: Deploy book

# Only run this when the master branch changes
on:
  push:
    branches: ["main"]

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
        #  channels: conda-forge,defaults
        #  channel-priority: true
        activate-environment: ols-stats
        environment-file: environment.yml
    - shell: bash -el {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
    - name: Build the book
      shell: bash -el {0}
      run: |
        jupyter-book build .
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html